# fly.toml app configuration file generated for my-app-chew3g on 2025-01-16T20:13:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-app-chew3g'
primary_region = 'atl'

[build]

[http_service]
  replicas = 1
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
